
Vagrant.configure("2") do |config|
  
# Web-server VM definition
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web-server"
    web.vm.network "private_network", ip: "192.168.56.101"
    web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: '127.0.0.1'
    web.vm.provider "virtualbox" do |vb|
      vb.name = "web"
      vb.memory = 1024
    end
    web.vm.provision "shell", path: "scripts/nginx_setup.sh"
  end

  # Database-server VM definition
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.102"
    db.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: '127.0.0.1'
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db"
      vb.memory = 2048
    end
    db.vm.provision "shell", path: "scripts/mysql_setup.sh"
  end

  
end
